kind: Service
apiVersion: v1
metadata:
  name: client-service
spec:
  selector:
    app: client-service
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
spec:
  selector:
      matchLabels:
        app: client-service
  replicas: 1
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
        - name: client-service
          image: localhost:5000/client-service:latest
          ports:
            - containerPort: 8080