kind: Service
apiVersion: v1
metadata:
  name: travel-agency-service
spec:
  selector:
    app: travel-agency-service
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-agency-service
spec:
  selector:
      matchLabels:
        app: travel-agency-service
  replicas: 2
  template:
    metadata:
      labels:
        app: travel-agency-service
    spec:
      containers:
        - name: travel-agency-service
          image: localhost:5000/travel-agency-service:latest
          ports:
          - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-password